#encoding UTF-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
EmsDatum.create(tagname: '储叶房湿度%RH',value:'1', group: '1')
EmsDatum.create(tagname: '储叶房温度℃',value:'2', group: '1')
EmsDatum.create(tagname: '储叶立体库湿度%RH',value:'3', group: '1')
EmsDatum.create(tagname: '储叶立体库温度℃',value:'4', group: '1')
EmsDatum.create(tagname: '封箱区湿度%RH',value:'5', group: '1')
EmsDatum.create(tagname: '封箱区温度℃',value:'6', group: '1')
EmsDatum.create(tagname: '辅料高架库东湿度%RH',value:'7', group: '1')
EmsDatum.create(tagname: '辅料高架库东温度℃',value:'8', group: '1')
EmsDatum.create(tagname: '辅料高架库西湿度%RH',value:'9', group: '1')
EmsDatum.create(tagname: '辅料高架库西温度℃',value:'10', group: '1')
EmsDatum.create(tagname: '加香装箱区湿度%RH',value:'11', group: '1')
EmsDatum.create(tagname: '加香装箱区温度℃',value:'12', group: '1')
EmsDatum.create(tagname: '滤棒作业区湿度%RH',value:'13', group: '1')
EmsDatum.create(tagname: '滤棒作业区温度℃',value:'14', group: '1')
EmsDatum.create(tagname: '软包区湿度%RH',value:'15', group: '1')
EmsDatum.create(tagname: '软包区温度℃',value:'16', group: '1')
EmsDatum.create(tagname: '手包烟区湿度%RH',value:'17', group: '1')
EmsDatum.create(tagname: '手包烟区温度℃',value:'18', group: '1')
EmsDatum.create(tagname: '送丝间北区湿度%RH',value:'19', group: '1')
EmsDatum.create(tagname: '送丝间北区温度℃',value:'20', group: '1')
EmsDatum.create(tagname: '送丝间南区湿度%RH',value:'21', group: '1')
EmsDatum.create(tagname: '送丝间南区温度℃',value:'22', group: '1')
EmsDatum.create(tagname: '箱装丝库湿度%RH',value:'23', group: '1')
EmsDatum.create(tagname: '箱装丝库温度℃',value:'24', group: '1')
EmsDatum.create(tagname: '烟丝暂存间湿度%RH',value:'25', group: '1')
EmsDatum.create(tagname: '烟丝暂存间温度℃',value:'26', group: '1')
EmsDatum.create(tagname: '硬包区湿度%RH',value:'27', group: '1')
EmsDatum.create(tagname: '硬包区温度℃',value:'28', group: '1')

EmsDatum.create(tagname: '动力中心电压/V',value:'29', group: '2')
EmsDatum.create(tagname: '负压/Mpa',value:'30', group: '2')
EmsDatum.create(tagname: '锅炉房供水压力/Mpa',value:'31', group: '2')
EmsDatum.create(tagname: '卷包车间电压/V',value:'32', group: '2')
EmsDatum.create(tagname: '卷包车间蒸汽压力/Mpa',value:'33', group: '2')
EmsDatum.create(tagname: '卷包工房给水压力/Kpa',value:'34', group: '2')
EmsDatum.create(tagname: '空压机总管压力/Bar',value:'35', group: '2')
EmsDatum.create(tagname: '立体车库电压/V',value:'36', group: '2')
EmsDatum.create(tagname: '联合工房供水压力/Mpa',value:'37', group: '2')
EmsDatum.create(tagname: '制丝车间电压/V',value:'38', group: '2')
EmsDatum.create(tagname: '制丝车间蒸汽压力/Mpa',value:'39', group: '2')
EmsDatum.create(tagname: '制丝工房给水压力/Kpa',value:'40', group: '2')

EmsDatum.create(tagname: '10号包装机_辅',value:'41', group: '4')
EmsDatum.create(tagname: '10号包装机_主',value:'42', group: '4')
EmsDatum.create(tagname: '10号机组空压气',value:'43', group: '4')
EmsDatum.create(tagname: '10号卷烟机',value:'44', group: '4')
EmsDatum.create(tagname: '11号包装机_辅',value:'45', group: '4')
EmsDatum.create(tagname: '11号包装机_主',value:'46', group: '4')
EmsDatum.create(tagname: '11号机组空压气',value:'47', group: '4')
EmsDatum.create(tagname: '11号卷烟机',value:'48', group: '4')
EmsDatum.create(tagname: '12号包装机_辅',value:'49', group: '4')
EmsDatum.create(tagname: '12号包装机_主',value:'50', group: '4')
EmsDatum.create(tagname: '12号机组空压气',value:'51', group: '4')
EmsDatum.create(tagname: '12号卷烟机',value:'52', group: '4')
EmsDatum.create(tagname: '13号包装机_辅',value:'53', group: '4')
EmsDatum.create(tagname: '13号包装机_主',value:'54', group: '4')
EmsDatum.create(tagname: '13号机组空压气',value:'55', group: '4')
EmsDatum.create(tagname: '13号卷烟机',value:'56', group: '4')
EmsDatum.create(tagname: '14号包装机_辅',value:'57', group: '4')
EmsDatum.create(tagname: '14号包装机_主',value:'58', group: '4')
EmsDatum.create(tagname: '14号机组空压气',value:'59', group: '4')
EmsDatum.create(tagname: '14号卷烟机',value:'60', group: '4')
EmsDatum.create(tagname: '15号包装机_辅',value:'61', group: '4')
EmsDatum.create(tagname: '15号包装机_主',value:'62', group: '4')
EmsDatum.create(tagname: '15号机组空压气',value:'63', group: '4')
EmsDatum.create(tagname: '15号卷烟机',value:'64', group: '4')
EmsDatum.create(tagname: '16号包装机_413',value:'65', group: '4')
EmsDatum.create(tagname: '16号包装机_703',value:'66', group: '4')
EmsDatum.create(tagname: '16号包装机_753',value:'67', group: '4')
EmsDatum.create(tagname: '16号机组空压气',value:'68', group: '4')
EmsDatum.create(tagname: '16号卷烟机',value:'69', group: '4')
EmsDatum.create(tagname: '17号包装机_413',value:'70', group: '4')
EmsDatum.create(tagname: '17号包装机_703',value:'71', group: '4')
EmsDatum.create(tagname: '17号包装机_753',value:'72', group: '4')
EmsDatum.create(tagname: '17号机组空压气',value:'73', group: '4')
EmsDatum.create(tagname: '17号卷烟机',value:'74', group: '4')
EmsDatum.create(tagname: '18号包装机_413',value:'75', group: '4')
EmsDatum.create(tagname: '18号包装机_703',value:'76', group: '4')
EmsDatum.create(tagname: '18号包装机_753',value:'77', group: '4')
EmsDatum.create(tagname: '18号机组空压气',value:'78', group: '4')
EmsDatum.create(tagname: '18号卷烟机',value:'79', group: '4')
EmsDatum.create(tagname: '19号包装机_413',value:'80', group: '4')
EmsDatum.create(tagname: '19号包装机_703',value:'81', group: '4')
EmsDatum.create(tagname: '19号包装机_753',value:'82', group: '4')
EmsDatum.create(tagname: '19号机组空压气',value:'83', group: '4')
EmsDatum.create(tagname: '19号卷烟机',value:'84', group: '4')

EmsDatum.create(tagname: '1号包装机_700',value:'85', group: '3')
EmsDatum.create(tagname: '1号包装机_750',value:'86', group: '3')
EmsDatum.create(tagname: '1号包装机_778',value:'87', group: '3')
EmsDatum.create(tagname: '1号机组空压气',value:'88', group: '3')
EmsDatum.create(tagname: '1号卷烟机',value:'89', group: '3')
EmsDatum.create(tagname: '2号包装机_700',value:'90', group: '3')
EmsDatum.create(tagname: '2号包装机_750',value:'91', group: '3')
EmsDatum.create(tagname: '2号包装机_778',value:'92', group: '3')
EmsDatum.create(tagname: '2号机组空压气',value:'93', group: '3')
EmsDatum.create(tagname: '2号卷烟机',value:'94', group: '3')
EmsDatum.create(tagname: '3号包装机_700',value:'95', group: '3')
EmsDatum.create(tagname: '3号包装机_750',value:'96', group: '3')
EmsDatum.create(tagname: '3号包装机_778',value:'97', group: '3')
EmsDatum.create(tagname: '3号机组空压气',value:'98', group: '3')
EmsDatum.create(tagname: '3号卷烟机',value:'99', group: '3')
EmsDatum.create(tagname: '4号包装机_700',value:'100', group: '3')
EmsDatum.create(tagname: '4号包装机_750',value:'101', group: '3')
EmsDatum.create(tagname: '4号包装机_778',value:'102', group: '3')
EmsDatum.create(tagname: '4号机组空压气',value:'103', group: '3')
EmsDatum.create(tagname: '4号卷烟机',value:'104', group: '3')
EmsDatum.create(tagname: '5号包装机_700',value:'105', group: '3')
EmsDatum.create(tagname: '5号包装机_750',value:'106', group: '3')
EmsDatum.create(tagname: '5号包装机_778',value:'107', group: '3')
EmsDatum.create(tagname: '5号机组空压气',value:'108', group: '3')
EmsDatum.create(tagname: '5号卷烟机',value:'109', group: '3')
EmsDatum.create(tagname: '6号包装机_辅',value:'110', group: '3')
EmsDatum.create(tagname: '6号包装机_主',value:'111', group: '3')
EmsDatum.create(tagname: '6号机组空压气',value:'112', group: '3')
EmsDatum.create(tagname: '6号卷烟机',value:'113', group: '3')
EmsDatum.create(tagname: '7号包装机_辅',value:'114', group: '3')
EmsDatum.create(tagname: '7号包装机_主',value:'115', group: '3')
EmsDatum.create(tagname: '7号机组空压气',value:'116', group: '3')
EmsDatum.create(tagname: '7号卷烟机',value:'117', group: '3')
EmsDatum.create(tagname: '8号包装机_辅',value:'118', group: '3')
EmsDatum.create(tagname: '8号包装机_主',value:'119', group: '3')
EmsDatum.create(tagname: '8号机组空压气',value:'120', group: '3')
EmsDatum.create(tagname: '8号卷烟机',value:'121', group: '3')
EmsDatum.create(tagname: '9号机组空压气',value:'122', group: '3')
EmsDatum.create(tagname: '9号卷烟机',value:'123', group: '3')







